---
title: "Thesis9.0"
author: "Hirsch"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
Conversions <- read.csv("~/Desktop/SENIOR THESIS/FINALDATA/ConversionsForProp.csv")


Conversions$LogGross_SQFT <- log(Conversions$Gross_SQFT)

Conversions

newpanel <- filter(Conversions, Gross_SQFT > 25000)
newpanel$Conv_Method <- as.factor(newpanel$Conv_Method)

```

Filter over 25,000 Square foot because there are economies of scale at play: both in terms of selecting into adaptive reuse and conversion and in terms of price per square foot. 

```{r} 
#This plot shows how There is a clisering of reuse among smaller conversions. especially in buildings below 5,000 Square feet. 
scatterplot3 <- ggplot(Conversions, aes(x = log(Gross_SQFT_2010), y = log(Gross_SQFT))) + 
  geom_point(aes(colour = factor(Conv_Method)))

scatterplot3 + plot_annotation(title = "Gross Square Feet after Office-to-Residential Conversion in NYC", subtitle = "From NYC DOF and DOB 2023")
```
```{r}
scatterplot3 <- ggplot(newpanel, aes(x = log(Gross_SQFT), y = log(PerSQFT_2023))) + 
  geom_point(aes(colour = factor(Conv_Method), shape = factor(BORO)))

scatterplot3 + plot_annotation(title = "Gross Square Feet after Office-to-Residential Conversion in NYC", subtitle = "Over 25,000 Square Feet, From NYC DOF and DOB 2023")
```

```{r}
my_data2 <- newpanel[, c("Conv_Method", "PerSQFT_2023", "PerResUnit", "Gross_SQFT", "CORNER", "TotalUnits", "BLD_Story", "BLD_Story_2010", "Land_Area", "FinMktTot_2010", "FinMktTot", "BORO", "OfficePerSQFT_2010", "OG_Year_Built_2010", "Gross_SQFT_2010")]

my_data2$Conv_Method <- as.factor(my_data2$Conv_Method)
my_data2$Conv_Method <- as.numeric(my_data2$Conv_Method)

my_data2$FinMktTot_2010 <- log(my_data2$FinMktTot_2010)
my_data2$FinMktTot <- log(my_data2$FinMktTot)
my_data2$PerResUnit <- log(my_data2$PerResUnit)
my_data2$BORO <- as.factor(my_data2$BORO)
my_data2$Gross_SQFT_2010 <- log(my_data2$Gross_SQFT_2010)
#my_data2$OfficePerSQFT_2010 <- log(my_data2$OfficePerSQFT_2010)


my_data2 <- dummy_cols(my_data2, remove_first_dummy = FALSE)
newnames <- dummy_cols(my_data2, remove_first_dummy = FALSE, return_generated_variables = TRUE)

#my_data2$BORO_Bronx <- as.numeric(mydata2$BORO_Bronx)

my_data2$BORO <- NULL

my_data2

simplecor2 <- cor(my_data2)
round(simplecor2, 2)

#Conv_Method <- Total Units, Delta, Retail, is sig correlated - Per Res Unit
#Corner <- Retail, Total Units, FinMktTot, FinMktTot_2010
#Hotel Area <- Total Units, Delta, FinMktTot_2010, FinMktTot
#Office Area <- Delta
#Retail strongly correlated with Everything
#Loft NAs
#Factory NA
#Total Units <- Conv_Method, CORNER, Delta, FinMktTot, FinMktTot_2010, Retail Hotel Area
#Delta <- Conv_Method, CORNER, FinMktTot, FinMktTot_2010, Retail Hotel Area, Total Units
#FinMktTot_2010 <- everything except office and conversion method
#FinMktTot <- everything except office and conversion method - Per Res Unit

#Per Res Unit <- correlated with Conv_Method and FinMktTot


corrplot2 <- rcorr(as.matrix(my_data2))

corrplot2$P <- corrplot2$P %>% replace(is.na(.), 0)

correlationmatrix2 <- corrplot(corrplot2$r, type = "upper", order = 'original', 
         p.mat = corrplot2$P, sig.level = 0.05, insig = "blank", tl.col = "black", tl.cex = 0.8)
```

```{r}
newpanel <- newpanel %>% mutate(log2010PerSQFT = log(OfficePerSQFT_2010)) #log PerSQFT_2010 control
newpanel <- newpanel %>% mutate(logBLD_Story = log(BLD_Story)) #log PerSQFT_2010 control
newpanel <- newpanel %>% mutate(logFinMktTot_2010 = log(FinMktTot_2010))
newpanel <- newpanel %>% mutate(logBLD_Story_2010 = log(BLD_Story_2010))
newpanel <- newpanel %>% mutate(logGross_SQFT_2010 = log(Gross_SQFT_2010))
newpanel <- newpanel %>% mutate(logGross_SQFT = log(Gross_SQFT))

newpanel <- filter(newpanel, BORO != "Staten Island")

OLSSQ1 <- lm(log(PerSQFT_2023) ~ Conv_Method, data = newpanel) #Raw difference ~94% sig
#OLSSQ2 <- lm(log(PerSQFT_2023) ~ Conv_Method + logGross_SQFT, data = newpanel) # ~93% sig
OLSSQ3 <- lm(log(PerSQFT_2023) ~ Conv_Method + logGross_SQFT_2010, data = newpanel) #~51% not sig
OLSSQ4 <- lm(log(PerSQFT_2023) ~ Conv_Method + logGross_SQFT_2010 + logGross_SQFT, data = newpanel) #21% not sig
OLSSQ6 <- lm(log(PerSQFT_2023) ~ Conv_Method + logGross_SQFT + logBLD_Story_2010 + logFinMktTot_2010 + logGross_SQFT_2010 + BORO, data = newpanel) #kitchen sink ~25%

summary(OLSSQ6)
#My estimates vary a lot but are all in the same direction. Still not very robust.  
```


```{r}


#Assessing variable balance
m.out0 <- matchit(Conv_Method ~ Land_Area + BORO + log2010PerSQFT + logGross_SQFT_2010 + log2010PerSQFT + logFinMktTot_2010 + logBLD_Story_2010,
                  data = newpanel,
                  method = NULL,
                  distance = "glm")

plot(summary(m.out0))
```

```{r}
M_nearest1 <- matchit(Conv_Method ~ logGross_SQFT_2010 + logFinMktTot_2010 + logBLD_Story_2010, data = newpanel, method = "full", link = "probit")
M_nearest2 <- matchit(Conv_Method ~ logGross_SQFT_2010 + logFinMktTot_2010 + logBLD_Story_2010, data = newpanel, method = "cem", link = "probit")

summary(M_nearest2) #table of balance

love.plot(M_nearest1, binary = "std")
love.plot(M_nearest2, binary = "std") #graph of balance

m.data1 <- match.data(M_nearest2)

dTot <- lm(log(PerSQFT_2023) ~ Conv_Method, m.data1, weights = weights)
print(dTot) # Estimate for dTot ~67%

MatchingEstimate1 <- lm(log(PerSQFT_2023) ~ Conv_Method + BORO + logGross_SQFT, m.data1, weights = weights)
summary(MatchingEstimate1) #~66%

m.data1
```
```{r}
stargazer(OLSSQ1, OLSSQ3, OLSSQ4, OLSSQ5, dTot, MatchingEstimate1, title="Results for Value per Square Foot", align=TRUE)
```

