---
title: "Thesis 3.5"
author: "Hirsch"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("~/Desktop/SENIOR THESIS")
library(ggplot2)
library(dplyr)
```




```{r}

#T_10 <- read.csv("~/Desktop/SENIOR THESIS/Final CSV/T_10.csv")
#T_11 <- read.csv("~/Desktop/SENIOR THESIS/Final CSV/T_11.csv")
#T_12 <- read.csv("~/Desktop/SENIOR THESIS/Final CSV/T_12.csv")
#T_13 <- read.csv("~/Desktop/SENIOR THESIS/Final CSV/T_13.csv")
#T_14 <- read.csv("~/Desktop/SENIOR THESIS/Final CSV/T_14.csv")
#T_15 <- read.csv("~/Desktop/SENIOR THESIS/Final CSV/T_15.csv")
#T_16 <- read.csv("~/Desktop/SENIOR THESIS/Final CSV/T_16.csv")
#T_17 <- read.csv("~/Desktop/SENIOR THESIS/Final CSV/T_17.csv")
#T_18 <- read.csv("~/Desktop/SENIOR THESIS/Final CSV/T_18.csv")
#T_19 <- read.csv("~/Desktop/SENIOR THESIS/Final CSV/T_19.csv")
T_20 <- read.csv("~/Desktop/SENIOR THESIS/Final CSV/T_20.csv")
T_21 <- read.csv("~/Desktop/SENIOR THESIS/Final CSV/T_21.csv")
T_22 <- read.csv("~/Desktop/SENIOR THESIS/Final CSV/T_22.csv")
T_23 <- read.csv("~/Desktop/SENIOR THESIS/Final CSV/T_23.csv")
```

```{r}
head(T_20)
```


```{r}
heading1 <- c("X","BBLE","BORO", "BLOCK", "LOT","EASE", "SUBIDENT_REUC", "RECTYPE", "YEAR", "IDENT",
              "SUBIDENT","ROLL_SECTION","SECVOL", "PYMKTLAND", "PYMKTTOT", "PYACTLAND", "PYACTTOT" , "PYACTEXTOT", "PYTRNLAND", "PYTRNTOT", 
      "PYTRNEXTOT", "PYTXBTOT", "PYTXBEXTOT", "PYTAXCLASS" , "TENMKTLAND","TENMKTTOT","TENACTLAND","TENACTTOT","TENACTEXTOT", "TENTRNLAND",
  "TENTRNTOT", "TENTRNEXTOT", "TENTXBTOT", "TENTXBEXTOT", "TENTAXCLASS", "CBNMKTLAND","CBNMKTTOT","CBNACTLAND","CBNACTTOT","CBNACTEXTOT",
"CBNTRNLAND","CBNTRNTOT", "CBNTRNEXTOT", "CBNTXBTOT", "CBNTXBEXTOT", "CBNTAXCLASS", "FINMKTLAND", "FINMKTTOT", "FINACTLAND", "FINACTTOT",
"FINACTEXTOT", "FINTRNLAND", "FINTRNTOT", "FINTRNEXTOT" ,"FINTXBTOT", "FINTXBEXTOT", "FINTAXCLASS", "CURMKTLAND", "CURMKTTOT", "CURACTLAND",
"CURACTTOT","CURACTEXTOT","CURTRNLAND","CURTRNTOT", "CURTRNEXTOT", "CURTXBTOT", "CURTXBEXTOT","CURTAXCLASS", "PERIOD", "NEWDROP",
"NOAV", "VALREF", "BLDG_CLASS", "OWNER", "ZONING" , "HOUSENUM_LO", "HOUSENUM_HI", "STREET_NAME", "ZIP_CODE", "GEOSUPPORT_RC",
"STCODE", "LOT_FRT", "LOT_DEP", "LOT_IRREG", "BLD_FRT", "BLD_DEP", "BLD_EXT", "BLD_STORY", "CORNER", "LAND_AREA",
"NUM_BLDGS", "YRBUILT", "YRBUILT_RANGE", "YRBUILT_FLAG", "YRALT1", "YRALT1_RANGE", "YRALT2", "YRALT2_RANGE", "COOP_APTS", "UNITS",
"REUC_REF", "APTNO", "COOP_NUM", "CPB_BORO", "CPB_DIST", "APPT_DATE", "APPT_BORO", "APPT_BLOCK", "APPT_LOT", "APPT_EASE", 
"CONDO_Number", "CONDO_SFX1", "CONDO_SFX2","CONDO_SFX3","UAF_LAND","UAF_BLDG", "PROTEST_1", "PROTEST_2", "PROTEST_OLD", "ATTORNEY_GROUP1", 
"ATTORNEY_GROUP2", "ATTORNEY_GROUP_OLD", "GROSS_SQFT", "HOTEL_AREA_GROSS","OFFICE_AREA_GROSS",
"RESIDENTIAL_AREA_GROSS","RETAIL_AREA_GROSS","LOFT_AREA_GROSS","FACTORY_AREA_GROSS","WAREHOUSE_AREA_GROSS",

"STORAGE_AREA_GROSS","GARAGE_AREA","OTHER_AREA_GROSS","REUC_DESCRIPTION","EXTRACTDT","PYTAXFLAG","TENTAXFLAG","CBNTAXFLAG","FINTAXFLAG","CURTAXFLAG",

"V140")

colnames(T_20) <- heading1

head(T_20)
```

```{r}
write.csv(T_23, "~/Desktop/SENIOR THESIS/Final CSV/T_23.csv")
```

